name 'jlyheden-nscd'
version '0.0.1'
source 'git@github.com:jlyheden/puppet-nscd.git'
author 'Johan Lyheden'
license 'Apache License 2.0'
project_page 'https://github.com/jlyheden/puppet-nscd'
summary 'Puppet nscd Module'
description 'Puppet module for managing the nscd daemon'
dependency 'puppetlabs/stdlib', '>=2.6.0'
