name 'artisol-nscd'
version '0.0.1'
source 'git@bitbucket.org:jlyheden/puppet-nscd.git'
author 'Johan Lyheden'
license 'TBD'
project_page 'https://bitbucket.org/jlyheden/puppet-nscd'
summary 'NSCD Module'
description 'Module for managing the NSCD daemon'
dependency 'puppetlabs/stdlib', '>=3.2.0'
